### ISSUE TITLE
Topography Error for SST app

### ISSUE THREAD

**Issue by j-harbin** [dankelley/teaching_shiny#2]
When clicking the topography toggle on the sea-surface temperature app, found at https://services.dal.ace-net.ca/shiny/dkelley/2020/globe_view/, I receive the following error:

![Screen Shot 2020-08-31 at 7 35 56 AM](https://user-images.githubusercontent.com/58750538/91711674-a4a4be00-eb5c-11ea-8e1a-d1104ba3a257.png)

It does note in the help page that "Some displays (e.g. topography) ignore the Colour Theme." however that does not align with this error.

**Comment by dankelley** [comment]
Fixed in "master" commit 8b7ba1f4a01d1e840a518f654b1094ce7564734a

NOTE: it will take approximately 30 minutes for this change to propagate to the teaching website, but running the app within this repository will demonstrate whether I've fixed the problem.
