### ISSUE TITLE
Axes for density in SST app not a superscript

### ISSUE THREAD

**Issue by j-harbin** [dankelley/teaching_shiny#3]
I noticed for the SST app found at https://services.dal.ace-net.ca/shiny/dkelley/2020/globe_view/, the density axis has the following units: [kg/m^3].

It seems in the next app created, showing how seawater density depends on salinity, temperature and pressure (https://services.dal.ace-net.ca/shiny/dkelley/2020/seawater_density/) you learned how to make the axis title have a superscript as shown below:
![Screen Shot 2020-08-31 at 7 40 54 AM](https://user-images.githubusercontent.com/58750538/91712026-5512c200-eb5d-11ea-8ad5-5063d48e3b0f.png)

This is not a major issue, just noteworthy if you want consistency.

**Comment by dankelley** [comment]
Fixed in "master" branch, commit b91bdfcd0dd872ab868bf3ebd6f71f5a3034ea3f.

NOTE: it will take approximately 30 minutes to propagate to the teaching site, but running it within this repo will demonstrate whether I've fixed the problem.
