### ISSUE TITLE
Temperature axes units very between apps

### ISSUE THREAD

**Issue by j-harbin** [dankelley/teaching_shiny#4]
Same idea as issue 3, for the SST app found at https://services.dal.ace-net.ca/shiny/dkelley/2020/globe_view/, the temperature axes has units [degC]. In the app that shows how seawater potential temperature depends on salinity, temperature and pressure (https://services.dal.ace-net.ca/shiny/dkelley/2020/seawater_potential_temperature/), the temperature units are as follows:

![Screen Shot 2020-08-31 at 7 45 27 AM](https://user-images.githubusercontent.com/58750538/91712355-f568e680-eb5d-11ea-8b08-05322607d4cb.png)

Again, not a major issue, I like know you like consistency.

**Comment by dankelley** [comment]
I've fixed the globe_view app, so this should be okay now.

NOTE: it will take approximately 30 minutes for this change to propagate to the teaching website, but running the app within this repository will demonstrate whether I've fixed the problem.
