### ISSUE TITLE
Should solar angle app have a space before unit

### ISSUE THREAD

**Issue by j-harbin** [dankelley/teaching_shiny#6]
For the app that shows how solar angles vary with observing location and time (https://services.dal.ace-net.ca/shiny/dkelley/2020/stick_shadow/), should the units have a space after the number? This is shown below:

![Screen Shot 2020-08-31 at 7 59 18 AM](https://user-images.githubusercontent.com/58750538/91713305-e4b97000-eb5f-11ea-9ce0-f08b5808a9d8.png)

This applies to the "help" window as well.

**Comment by dankelley** [comment]
Done in "master" commit  e1a15f45a5dab097b03a3dc7ef49135d779368de 

NOTE: it will take approximately 30 minutes for this change to propagate to the teaching website, but running the app within this repository will demonstrate whether I've fixed the problem.

**Comment by j-harbin** [comment]
Note this also applies to the "help" page when it says "The thick radial line shows shadows from a 2cm tall vertical stick, and the thinner line connects"

**Comment by dankelley** [comment]
I updated the help page in commit 7be0b213bf979274fe47c379f2997d75661c8df3

**Comment by dankelley** [comment]
I'm closing this since it has been done.
