### ISSUE TITLE
Help page closes out on solar angle app

### ISSUE THREAD

**Issue by j-harbin** [dankelley/teaching_shiny#7]
For the app that shows how solar angles vary with observing location and time (https://services.dal.ace-net.ca/shiny/dkelley/2020/stick_shadow/)

While reading the help page it closed out and I was required to continue to reclick it as I was reading it. I didn't notice this with the other apps.

**Comment by dankelley** [comment]
Done in "master" commit e790b20f51eedc51d1f7058370f6c51befe86760

NOTE: it will take approximately 30 minutes for this change to propagate to the teaching website, but running the app within this repository will demonstrate whether I've fixed the problem.
