### ISSUE TITLE
argo_floats should have checkboxes for type

### ISSUE THREAD

**Issue by dankelley** [dankelley/teaching_shiny#9]
Types: `core`, `bgc` and `deep`.

**Comment by dankelley** [comment]
For `bgc`, I thought I could do as follows, but when I do that, `sum(bgc)` is zero, indicating no hits.  Any ideas, @j-harbin?
```R
library(argoFloats)
i <- getIndex()
deep <- grepl("849|862|864", i@data$index$profiler_type)
bgc <- grepl("profile/B", i@data$index$file)
```

**Comment by j-harbin** [comment]
Hi Dan,

I would have a similar approach, shown below:

```R
library(argoFloats)
data("indexBgc")
indexBgc[['file',1]]
```
produces
```R
aoml/4900845/profiles/BR4900845_086.nc
```
Where the "B" in the name indicates BGC Argo. We therefore would do a grepl to isolate filenames within index that have the B as follow:

```R
bgc <- grepl("^[a-z]*/[0-9]*/profiles/B[A-Z].*$", indexBgc[["file"]])
sum(bgc)
```
produces
```R
[1] 39
```
In your case,  the `getIndex()` is core data (ie. the file names would not have a B in them), but in my case I used the `indexBgc` and therefore got 39 hits. Does this make sense?

**Comment by dankelley** [comment]
So, there's nothing in the core index to tell us that the profile also has bgc data paired with it?

**Comment by j-harbin** [comment]
No, my understand is that is what the "merged" dataset is.

**Comment by dankelley** [comment]
Hm. This means that, for this mapping application, it will be necessary to find all the IDs in a "merged" dataset, and then see which entries in the "core" dataset are in that list of IDs.  That's kind of a hassle to code and maybe slow to execute, so I was guessing that (like with `profiler_type`) they would a flag in the basic index.

Anyway, for now, I've removed the button for BGC, in "master" branch commit d7290f62d6bece2b106afaf56344947ce9240d61

**Comment by dankelley** [comment]
For future reference, here is what I see.  There are a lot of profiler_type values.  I wonder, @j-harbin can you find a reference to a document that tells us what they mean?  There might be something good in there (even if not helpful to the present issue).

```R
> library(argoFloats)
> i <- getIndex()
> table(i@data$index[["profiler_type"]])

    831     835     836     838     840     841     842     843     844     845     846     847     849     851
   1033    2438   41527    3140    3107  111950    9898     391  182159    7611 1289184     547    2358  256112
    852     853     854     856     858     860     862     863     864     865     869     870     871     872
  40699  123413   86100     847     139   16885    6287  103537     554   24580    8675    2309     882    1374
    873     874     999
   4095    1718     351
```

**Comment by dankelley** [comment]
Wow, sometimes R just surprises me.  I had thought it might be slow to find out which IDs were of the bgc type, but look at the comment on the last line!  I can live with 1/50-th of a second!  I guess R is built to do such things quickly, since it's a kind of stats-y thing to do :-) Anyway, I'll be using this when I work on the argo_map app tomorrow.
```R
library(argoFloats)
i <- getIndex()
n <- i[["length"]]
id <- i[["id"]]                        # 2333900 elements (16381 unique) as of 2020-08-31
n <- length(id)
iBGC <- getIndex("bgc")
idBGC <- unique(iBGC[["id"]])          # 1410 unique elements as of 2020-08-31
type <- rep("core", n)
system.time(type[id %in% idBGC] <- "bgc") # only 0.02 seconds elapsed time!
```

**Comment by dankelley** [comment]
PS the `type` line above is also amazing.  I had thought that I would want to make a `factor` to save storage, but it turns out that with present-day R, repeats within a vector of string just use pointers, so there's no problem making a long vector of strings that can have only a few values.  Again, I can see why they would want it to be this way (think of long species names, for example).

**Comment by dankelley** [comment]
Oh, this was done a while ago but I forgot to close it.
